version: '3'

services:
  api:
    build: .
    ports: 
     - "80:80"
     - "9100:9100"

  prometheus:
    image: "prom/prometheus:latest"
    ports: 
     - "9090:9090"
    volumes:
      - /prometheus/:/etc/prometheus/
    restart: always
  # grafana:
  #   image: grafana/grafana
  #   user: "472"
  #   depends_on:
  #     - prometheus
  #   ports:
  #     - "3000:3000"
  #   #volumes:
  #   #  - ./grafana/provisioning/:/etc/grafana/provisioning/
  #   #env_file:
  #   #  - ./grafana/config.monitoring
  #   restart: always